### PR TITLE
add support for mic sharing

### PR DESCRIPTION
**Pull request by sdetweil**
enable requestor to stop pocketsphinx and restart to allow mic sharing with other modules and apps

### CODE REVIEW

**Comment by fewieden** [comment]
Hi @sdetweil I didn't get a chance to look into your pull request earlier.

From what I can see is that your indentation is broken.

Also I'm not sure if this is the right approach to do it (self and global variables).

I think it would be better to extend the prototype.

**Comment by sdetweil** [comment]
ok, have a look, I didn't know about this approach.. thanks for the push to learn..

**Comment by fewieden** [comment]
@sdetweil I cleaned up the code. I currently have no test setup with me as I'm on vacation. Would it be possible for you to test that my changes didn't break anything? Be aware of, that I changed the start and stop functions.

**Comment by sdetweil** [comment]
looks great..   i like the other function names better, but no matter..

**Pull request merged**
